[build]
  command = "echo \"const SUPABASE_URL = '$SUPABASE_URL'; const SUPABASE_ANON = '$SUPABASE_ANON';\" > frontend/config.js"
  publish = "frontend"

[build.environment]
  SECRETS_SCAN_OMIT_PATHS = "frontend/config.js"